### ISSUE TITLE
End not working

### ISSUE THREAD

**Issue by hiprof** [espen96/Loop#18]
When entering the end
![2021-04-16_15 34 37](https://user-images.githubusercontent.com/45518409/115032169-51079a80-9ec9-11eb-8868-1234eb19c05b.png)

After dying to the void there
![2021-04-16_15 02 17](https://user-images.githubusercontent.com/45518409/115029346-2ec04d80-9ec6-11eb-9f77-2f047524eebd.png)

Mc: 1.16.4 + Forge + Optifine G6

Loop-Beta-2

Graphics card: Nvidia GTX 1060

**Comment by Alibaba4369** [comment]
use the latest commit, not the latest release

**Comment by hiprof** [comment]
Now working
