### ISSUE TITLE
Enchantment glint is glitched.

### ISSUE THREAD

**Issue by johannesspinnenschreck** [espen96/Loop#2]
When you equip an enchanted item or hold one in the hand it's glint is glitched.

![2020-08-03_01 26 19](https://user-images.githubusercontent.com/69090516/89134811-5f26ae00-d528-11ea-96d5-874af3a5bed8.png)

**Comment by johannesspinnenschreck** [comment]
It got kind of fixed, but the glint is way too much.
![2020-08-04_16 29 09](https://user-images.githubusercontent.com/69090516/89306178-cd29bd00-d66f-11ea-9c4a-481bd11570ae.png)

**Comment by espen96** [comment]
I'll get that sorted
