### ISSUE TITLE
Lighting issue for 1.16 nether plants

### ISSUE THREAD

**Issue by mystjc** [espen96/Loop#7]
The lighting of the 1.16 nether plants are inconsistent compared to other plants. The face of the plant pointed away from the sun is unlight. This happens when using the latest release: Loop Beta 2. Not sure if it has been fixed in a new unreleased version. Red and brown mushrooms are for reference.
![lightingIssue](https://user-images.githubusercontent.com/77810795/105424013-824b3400-5c14-11eb-98bb-d7ab23a6ae0f.png)

**Comment by espen96** [comment]
Ah yes, I'll get that sorted

**Comment by mystjc** [comment]
Cool, it not a major issue so take your time
